import Head from "next/head";
import Image from "next/image";
import Header from "@/components/Header/Header";
import RegisterForm from "@/components/RegisterForm/RegisterForm";
import {
  Box,
  Flex
} from "@chakra-ui/react";


import logo from "@/public/logo_dark.png";

import loginBg from "@/public/auth_bg.png";
export default function Login() {
  return (
    <>
      <Head>
        <title>Register page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <Flex backgroundColor={"#141414"}>
        <Box flex="1" position="relative">
          <Image src={loginBg} alt="Login background" />
          <Box
            position="absolute"
            top="50%"
            left="50%"
            transform="translate(-50%, -50%)"
            zIndex="10"
          >
            <Image src={logo} alt="Logo" width="300" height="300" />
          </Box>
        </Box>
        <Box flex="1" bg="gray.50">
          <RegisterForm />
        </Box>
      </Flex>
    </>
  );
}